version: '2.4'
services:
  workspace:
    # env_file:
    #   - .env
    image: ghcr.io/ngxingyu/ros-devcontainer:noetic-desktop
    ipc: host
    network_mode: host
    security_opt:
      - seccomp:unconfined
    volumes:
      - auv_workspace:/workspace # persist the devel / install folder across sessions
      - ../bbauv_ws/src:/workspace/src # bind-mount auv workspace
      # - asv_workspace:/workspace # persist the devel / install folder across sessions
      # - ../bbasv_ws/src:/workspace/src # bind-mount asv workspace
    environment:
      - DISPLAY=${DISPLAY}
      - VGL_CLIENT=${VGL_CLIENT}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
    devices:
      - /dev/dri:/dev/dri
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
volumes:
  asv_workspace: # volume
  auv_workspace: # volume
